name: dofix_technichian
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.2+34

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.2.3
  carousel_slider: ^5.1.1
  shared_preferences: ^2.5.4
  http: ^1.6.0
  file_picker: ^10.3.8
  image_picker: ^1.2.1
  dotted_border: ^2.1.0
  numberpicker: ^2.1.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  geolocator: ^14.0.2
  flutter_html: ^3.0.0
  intl: ^0.20.2
  google_maps_flutter: ^2.14.0
  google_places_flutter: ^2.1.1
  geocoding: ^4.0.0
  camera: ^0.11.3
  syncfusion_flutter_gauges: ^32.1.21
  flutter_card_swiper: ^7.2.0
  fl_chart: ^1.1.1
  flutter_polyline_points: ^3.1.0
  url_launcher: ^6.3.2
  freezed: ^3.2.3
  json_annotation:
  universal_html: ^2.3.0
  just_the_tooltip: ^0.0.12
  flutter_inappwebview: ^6.1.5
  video_thumbnail: ^0.5.6
  video_player: ^2.10.1
  change_app_package_name: ^1.5.0
  qr_flutter: ^4.1.0
  in_app_update: ^4.2.5
  google_fonts: ^8.0.0
  firebase_messaging: ^16.1.1
  firebase_core: ^4.4.0
  mobile_scanner: ^7.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/img/vice/
    - assets/img/logo/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/AlbertSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/AlbertSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/AlbertSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/AlbertSans-SemiBold.ttf
          weight: 600
